function dxdt=f(x,u)
 
%         p=params();
        M = testMatrixM(x(1),x(2),x(3),x(4),x(5));
        C = testMatrixC(x(1),x(2),x(3),x(4),x(5),x(6),x(7),x(8),x(9),x(10)); 
        T = testMatrixT(x(1),x(2),x(3),x(4),x(5));
%         [M,C,T]=MCT(x);
         B = eye(5);
       
    
        dxdt = zeros(10,1);
        dxdt(1) = x(6);
        dxdt(2) = x(7);
        dxdt(3) = x(8);
        dxdt(4) = x(9);
        dxdt(5) = x(10);
        k =inv(M)*(-C - T)+ inv(M)*B*[u(1);u(2);u(3);u(4);u(5)];
        %k =inv(M)*B*U_optimal;
        dxdt(6) = k(1);
        dxdt(7) = k(2);
        dxdt(8) = k(3);
        dxdt(9) = k(4);
        dxdt(10) = k(5);

end






% 
% function f = f(in1)
% %F
% %    F = F(IN1)
% 
% %    This function was generated by the Symbolic Math Toolbox version 8.3.
% %    08-Nov-2019 09:59:54
% 
% 
% 
% dth_st = in1(4,:);
% dth_sw = in1(3,:);
% th_st = in1(2,:);
% th_sw = in1(1,:);
% t2 = sin(th_st);
% t3 = sin(th_sw);
% t4 = dth_st.^2;
% t5 = dth_sw.^2;
% t6 = -th_sw;
% t7 = t6+th_st;
% t8 = cos(t7);
% t9 = sin(t7);
% t10 = t8.^2;
% t11 = t10.*4.0;
% t12 = t11-1.3e+1;
% t13 = 1.0./t12;
% f = [dth_sw;dth_st;t13.*(t3.*6.37e+2-t2.*t8.*6.86e+2+t4.*t9.*6.5e+1-t5.*t8.*t9.*1.0e+1).*(2.0./5.0);t13.*(t2.*3.43e+2-t3.*t8.*9.8e+1+t5.*t9.*5.0-t4.*t8.*t9.*1.0e+1).*(-2.0./5.0)];
