function Msubbed = testMatrixM(th1,th2,th3,th4,th5)
%TESTMATRIXM
%    MSUBBED = TESTMATRIXM(TH1,TH2,TH3,TH4,TH5)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 01:03:23

t2 = th1+th4;
t3 = th1+th5;
t4 = th2+th4;
t5 = th2+th5;
t10 = -th2;
t11 = -th3;
t12 = -th5;
t6 = cos(t2);
t7 = cos(t3);
t8 = cos(t4);
t9 = cos(t5);
t13 = t10+th1;
t14 = t11+th1;
t15 = t11+th2;
t16 = t12+th4;
t17 = cos(t13);
t18 = cos(t14);
t19 = cos(t15);
t20 = cos(t16);
t21 = t6.*(4.38e+2./6.25e+2);
t22 = t8.*(4.38e+2./6.25e+2);
t23 = t7.*1.60512e-1;
t24 = t9.*1.60512e-1;
t25 = t18.*(3.79e+2./1.25e+2);
t26 = t19.*(3.79e+2./1.25e+2);
t27 = t20.*1.60512e-1;
t28 = t17.*5.51488;
Msubbed = reshape([5.9998992,t28,t25,t21,t23,t28,5.38876,t26,t22,t24,t25,t26,3.15875,0.0,0.0,t21,t22,0.0,5.7468e-1,t27,t23,t24,0.0,t27,1.052432e-1],[5,5]);
