function Tsubbed = testMatrixT(th1,th2,th3,th4,th5)
%TESTMATRIXT
%    TSUBBED = TESTMATRIXT(TH1,TH2,TH3,TH4,TH5)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 01:03:24

Tsubbed = [sin(th1).*(-1.85628744e+2);sin(th2).*(-1.6906554e+2);sin(th3).*(-9.294975e+1);sin(th4).*2.14839e+1;sin(th5).*4.920696];
