function Csubbed = testMatrixC(th1,th2,th3,th4,th5,th1dot,th2dot,th3dot,th4dot,th5dot)
%TESTMATRIXC
%    CSUBBED = TESTMATRIXC(TH1,TH2,TH3,TH4,TH5,TH1DOT,TH2DOT,TH3DOT,TH4DOT,TH5DOT)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    10-Dec-2019 01:03:23

t2 = th1+th4;
t3 = th1+th5;
t4 = th2+th4;
t5 = th2+th5;
t6 = th1dot.^2;
t7 = th2dot.^2;
t8 = th3dot.^2;
t9 = th4dot.^2;
t10 = th5dot.^2;
t15 = -th2;
t16 = -th3;
t17 = -th5;
t11 = sin(t2);
t12 = sin(t3);
t13 = sin(t4);
t14 = sin(t5);
t18 = t15+th1;
t19 = t16+th1;
t20 = t16+th2;
t21 = t17+th4;
t22 = sin(t18);
t23 = sin(t19);
t24 = sin(t20);
t25 = sin(t21);
Csubbed = [t9.*t11.*(-4.38e+2./6.25e+2)-t10.*t12.*1.60512e-1+t7.*t22.*5.51488+t8.*t23.*(3.79e+2./1.25e+2);t9.*t13.*(-4.38e+2./6.25e+2)-t10.*t14.*1.60512e-1-t6.*t22.*5.51488+t8.*t24.*(3.79e+2./1.25e+2);t6.*t23.*(-3.79e+2./1.25e+2)-t7.*t24.*(3.79e+2./1.25e+2);t6.*t11.*(-4.38e+2./6.25e+2)-t7.*t13.*(4.38e+2./6.25e+2)+t10.*t25.*1.60512e-1;t6.*t12.*(-1.60512e-1)-t7.*t14.*1.60512e-1-t9.*t25.*1.60512e-1];
