function f = f(in1)
%F
%    F = F(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    08-Nov-2019 09:59:54

dth_st = in1(4,:);
dth_sw = in1(3,:);
th_st = in1(2,:);
th_sw = in1(1,:);
t2 = sin(th_st);
t3 = sin(th_sw);
t4 = dth_st.^2;
t5 = dth_sw.^2;
t6 = -th_sw;
t7 = t6+th_st;
t8 = cos(t7);
t9 = sin(t7);
t10 = t8.^2;
t11 = t10.*4.0;
t12 = t11-1.3e+1;
t13 = 1.0./t12;
f = [dth_sw;dth_st;t13.*(t3.*6.37e+2-t2.*t8.*6.86e+2+t4.*t9.*6.5e+1-t5.*t8.*t9.*1.0e+1).*(2.0./5.0);t13.*(t2.*3.43e+2-t3.*t8.*9.8e+1+t5.*t9.*5.0-t4.*t8.*t9.*1.0e+1).*(-2.0./5.0)];
