function f = f(x,u)
%F
%    F = F(X,U)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Oct-2018 09:42:42

pdot = x(3,:);
thetadot = x(4,:);
theta = x(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t4-2.0;
t6 = 1.0./t5;
t7 = thetadot.^2;
f = [pdot;thetadot;t6.*(u.*1.0e2+t2.*t3.*9.81e2+t3.*t7.*1.0e2).*(-1.0./1.0e2);t6.*(t3.*9.81e2+t2.*u.*5.0e1+t2.*t3.*t7.*5.0e1).*(1.0./5.0e1)];
